# =========================
# Envoy node identity (SDS required)
# =========================
node:
  id: ingress-envoy
  cluster: ingress-edge

static_resources:
  listeners:
  - name: ingress_https
    address:
      socket_address: { address: 0.0.0.0, port_value: 18080 }
    per_connection_buffer_limit_bytes: 32768
    filter_chains:
    - transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: false
          common_tls_context:
            tls_certificates:
            - certificate_chain: { filename: /etc/envoy/certs/localhost.crt }
              private_key:        { filename: /etc/envoy/certs/localhost.key }
            alpn_protocols: ["h2", "http/1.1"]

      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_hcm
          generate_request_id: true
          # preserve_external_request_id: true

          internal_address_config:
            unix_sockets: true
            cidr_ranges:
            - address_prefix: "10.0.0.0"
              prefix_len: 8
            - address_prefix: "172.16.0.0"
              prefix_len: 12
            - address_prefix: "192.168.0.0"
              prefix_len: 16

          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              log_format:
                json_format:
                  ts: "%START_TIME%"
                  method: "%REQ(:METHOD)%"
                  path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                  status: "%RESPONSE_CODE%"
                  response_flags: "%RESPONSE_FLAGS%"
                  upstream_cluster: "%UPSTREAM_CLUSTER%"
                  upstream_host: "%UPSTREAM_HOST%"
                  duration_ms: "%DURATION%"
                  user_agent: "%REQ(USER-AGENT)%"
                  jwt_sub: "%REQ(x-jwt-sub)%"
                  b3_traceid: "%REQ(x-b3-traceid)%"
                  traceparent: "%REQ(traceparent)%"
                  b3_traceid: "%REQ(x-b3-traceid)%"
                  b3_spanid: "%REQ(x-b3-spanid)%"
                  x_request_id: "%REQ(x-request-id)%"

          tracing:
            client_sampling:  { value: 100.0 }
            random_sampling:  { value: 100.0 }
            overall_sampling: { value: 100.0 }

          route_config:
            name: local_route
            virtual_hosts:
            - name: auth
              domains: ["*"]
              routes:
              - match: { path: "/v1/login" }
                decorator:
                  operation: "ingress -> auth"
                route:
                  cluster: auth_envoy
                  timeout: 15s
                typed_per_filter_config:
                  envoy.filters.http.cors:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                    allow_origin_string_match:
                    - exact: "http://localhost:3000"
                    allow_methods: "POST,OPTIONS"
                    allow_headers: "content-type,authorization"
                    expose_headers: "x-request-id"
                    allow_credentials: true
                    max_age: "86400"
              - match: { prefix: "/" }
                direct_response:
                  status: 404

          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: auth_envoy
      connect_timeout: 1s
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: auth_envoy
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: auth-envoy, port_value: 18080 }
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: "ingress-envoy"
          common_tls_context:
            tls_certificate_sds_secret_configs:
              - name: ingress-envoy
                sds_config:
                  resource_api_version: V3
                  api_config_source:
                    api_type: GRPC
                    transport_api_version: V3
                    grpc_services:
                      - envoy_grpc:
                          cluster_name: ingress_sds_uds
            validation_context_sds_secret_config:
              name: trusted_ca
              sds_config:
                resource_api_version: V3
                api_config_source:
                  api_type: GRPC
                  transport_api_version: V3
                  grpc_services:
                    - envoy_grpc:
                        cluster_name: ingress_sds_uds
            alpn_protocols: ["h2"]
      outlier_detection:
        consecutive_gateway_failure: 5
        interval: 5s
        base_ejection_time: 30s
        max_ejection_percent: 50

    # step-sds gRPC
    - name: ingress_sds_uds
      connect_timeout: 1s
      type: STATIC
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: ingress_sds_uds
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    pipe:
                      path: /var/run/step-sds/sds.sock

    - name: otel_collector_zipkin
      type: LOGICAL_DNS
      connect_timeout: 5s
      lb_policy: ROUND_ROBIN
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: otel_collector_zipkin
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: otel-collector
                  port_value: 9411

tracing:
  http:
    name: envoy.tracers.zipkin
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
      collector_cluster: otel_collector_zipkin
      collector_endpoint: "/api/v2/spans"
      collector_endpoint_version: HTTP_JSON
      trace_context_option: USE_B3_WITH_W3C_PROPAGATION
