server:
  port: 8082

cors:
  rules:
    - path: "/*"
      allowed_origins:
        - "*"

mysql:
  dsn: "auth:authpass@tcp(mysql:3306)/auth?parseTime=true"

redis:
  addr: "localhost:6379"
  password: "test123"
  db: 0
