server:
  port: 8081

cors:
  rules:
    - path: "/v1/*"
      allowed_origins:
        - "*"
    - path: "/v2/*"
      allowed_origins:
        - "https://app.example.com"
        - "https://cdn.example.com"
    - path: "/api/v1/admin/*"
      allowed_origins:
        - "https://admin.example.com"

mysql:
  dsn: "auth:authpass@tcp(mysql:3306)/auth?parseTime=true"

redis:
  addr: "redis:6379"
  password: ""
  db: 0

# generate a random secret key for JWT
# 32 bytes base64
#openssl rand -base64 32
# or hex:
#openssl rand -hex 32
jwt:
  secret: "L8hCW84Q5XiY2Z3aDT28UN1f3uUSgfcQdWlxy3GsB8Q="
  expire: 60

app:
  env: "dev"